# Generated by Django 6.0.4 on 2026-04-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('appointment_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('completed', 'Geldi'), ('no_show', 'Gelmedi')], default='scheduled', max_length=10)),
            ],
        ),
    ]
