# Generated by Django 6.0.4 on 2026-04-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_customer'),
        ('customers', '0002_customer_created_at_alter_customer_email'),
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='offerings.offering'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
    ]
