# Generated by Django 6.0.4 on 2026-04-30 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_offering_alter_appointment_customer'),
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='offering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='offerings.offering'),
            preserve_default=False,
        ),
    ]
